# Configuration for processing ROS2 bag files
# This file specifies the paths, storage format, and topics to extract from the ROS bag.

# Path to the input ROS2 bag file
bag_path: "/home/rborder/data/eagleeye/calibration/seq_50"

# Directory where the exported data will be saved
output_dir: "/home/rborder/data/eagleeye/calibration/seq_50"

# Storage format for the exported data. Options are "sqlite3" or "mcap"
storage_id: "sqlite3"

# List of topics to extract from the ROS2 bag
topics:
  # Configuration for the point cloud topic
  - name: "/livox/lidar"   # Name of the topic to extract
    type: "PointCloud2"         # Data type of the topic
    sample_interval: 1         # Write one sample every 10 messages

  # Configuration for the RGB image topic
  - name: "/cam0/image_raw"    # Name of the topic to extract
    type: "Image"               # Data type of the topic
    encoding: "rgb8"            # Encoding format for the image
    sample_interval: 100         # Write one sample every 5 messages

      # Configuration for the RGB image topic
  - name: "/cam1/image_raw"    # Name of the topic to extract
    type: "Image"               # Data type of the topic
    encoding: "rgb8"            # Encoding format for the image
    sample_interval: 100         # Write one sample every 5 messages

      # Configuration for the RGB image topic
  - name: "/cam2/image_raw"    # Name of the topic to extract
    type: "Image"               # Data type of the topic
    encoding: "rgb8"            # Encoding format for the image
    sample_interval: 100         # Write one sample every 5 messages


      # Configuration for the RGB image topic
  - name: "/cam3/image_raw"    # Name of the topic to extract
    type: "Image"               # Data type of the topic
    encoding: "rgb8"            # Encoding format for the image
    sample_interval: 100        # Write one sample every 5 messages